### ISSUE TITLE
git似乎没法用

### ISSUE THREAD

**Issue by terhh996** [deltaeecs/MoM_AllinOne.jl#6]
Cloning into 'MoM_AllinOne'...
remote: [session-084b6985] 404 not found!
fatal: repository 'https://gitee.com/deltaeecs/MoM_AllinOne.git/' not found
请问怎么解决？

**Comment by deltaeecs** [comment]
换到 github，或者访问(https://gitee.com/deltaeecs/MoM_AllinOne.jl)，但gitee好久没更新了，懒得维护，优先用github吧
